DROP TABLE IF EXISTS selection_records;

DROP TABLE IF EXISTS selections;

DROP TABLE IF EXISTS sections;

DROP TABLE IF EXISTS ratings;

DROP TABLE IF EXISTS courses;

DROP TABLE IF EXISTS admins;

DROP TABLE IF EXISTS teachers;

DROP TABLE IF EXISTS students;

DROP TABLE IF EXISTS trimesters;

DROP TABLE IF EXISTS nacionalities;

DROP TABLE IF EXISTS users;
